### ISSUE TITLE
Support obtaining MAINTAINER name/email from ~/.porttools

### ISSUE THREAD

**Issue by koobs** [freebsd/pytoport#1]
Users/contributors/maintainers that have _ports-mgmt/porttools_ installed, are asked to create a _~/.porttools_ file containing, among other things, their email address and full name, with format as follows:

~/.porttools

```
EMAIL="user@domain.tld"
FULLNAME="Firstname Lastname"
```

See `man 5 porttools` for more information.

It would be highly pleasurable if pytoport also supported obtaining the information from this source, if it exists.

**Comment by bbqsrc** [comment]
Fixed in [v0.2.0](https://github.com/freebsd/pytoport/releases/tag/v0.2.0).
