### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by samriang** [freebsd/pytoport#2]
Hi there.
I've got following error when trying to make 'python setup.py install' inside virtualenv 
http://pastebin.com/0QHrmRZf

I'm using jenkins on freebsd.
Is it my own issue or something related to sources?

Thanks in advance.

**Comment by bbqsrc** [comment]
The pastebin has expired.

**Comment by bbqsrc** [comment]
I seem to have reproduced the issue. The package depends on `spdx-lookup`, which depends upon `spdx`. The installer successfully installs `spdx-lookup`, but when looking for `spdx`, for some reason, **finds `spdx-lookup` instead** and fails.

To workaround this, install `spdx` in your virtualenv first.

**Comment by bbqsrc** [comment]
Also, I've changed the dependency field on `spdx-lookup` so it looks up `spdx` properly regardless of `easy_install`'s opinions. The command you tried should just work now.

**Comment by samriang** [comment]
yeah, all works lovely now
thank you :)
