### ISSUE TITLE
 PyPI: moto package -- LICENSE_FILE and RUN_DEPENDS not added

### ISSUE THREAD

**Issue by koobs** [freebsd/pytoport#5]
Using pytoport to create a port for the moto package, the following items were not created:
- `LICENSE_FILE=${WRKSRC}/LICENSE` (LICENSE file exists in WRKSRC)
- `RUN_DEPENDS` for packages listed in `setup.py:install_requires`

**Comment by bbqsrc** [comment]
Already does this, closing.
